# Site settings
title: Collection of my many mad ideas
description: Collection of my many mad ideas
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Callum Hutchinson
user_description: Software Developer with more ideas than time to create them
user_title: Software Developer
twitter_username: thecallumhutchy
github_username:  callumhutchy
linkedin_username: callum-hutchinson-65b2b6108


# Google-analytics
google-analytics:
  id: "UA-58279411-1"

exclude: ['package.json', 'src' , 'node_modules']
